### ISSUE TITLE
支持迅雷高速下载么？

### ISSUE THREAD

**Issue by michael-kj** [Greedysky/TTKDownloader#11]
emmm  是仿冒还是支持迅雷下载哇？

**Comment by Greedysky** [comment]
支持迅雷链接解析，速度看资源

**Comment by michael-kj** [comment]
> 支持迅雷链接解析，速度看资源

嗯嗯    那能高速通道么（自己是迅雷会员）
哈哈   命令行版本更香

**Comment by Greedysky** [comment]
> 
> 
> > 支持迅雷链接解析，速度看资源
> 
> 嗯嗯 那能高速通道么（自己是迅雷会员）
> 哈哈 命令行版本更香

已支持命令行
