### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by Stephen2252Ro** [Greedysky/TTKDownloader#13]
怎么使用啊老哥。把你的release里的源码下载到本地了

**Comment by Greedysky** [comment]
暂时需要自己手动编译源码

**Comment by Stephen2252Ro** [comment]
额 老哥有写好的makefile啥的吗。自己没有知道手动编译太难了些吧
&nbsp;


罗庆尧
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年6月19日(星期三) 中午1:36
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Greedysky/TTKDownloader] 怎么使用 (Issue #13)














 
暂时需要自己手动编译源码

**Comment by Greedysky** [comment]
> 额 老哥有写好的makefile啥的吗。自己没有知道手动编译太难了些吧 &nbsp; 罗庆尧 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: 2024年6月19日(星期三) 中午1:36 To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: Re: [Greedysky/TTKDownloader] 怎么使用 (Issue #13) 暂时需要自己手动编译源码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

用Qt自带的qmake就行，cmake那套我暂时还没有时间捣腾。

**Comment by Greedysky** [comment]
Done!
