### ISSUE TITLE
编译运行时缺少TTKService.sh

### ISSUE THREAD

**Issue by XxxAmericano** [Greedysky/TTKDownloader#14]
20:40:18: Starting /home/zzy/Qt/TTKDownloader-master/build/Desktop_Qt_5_15_0_GCC_64bit-Debug/bin/TTKDownloader...
sh: 1: /home/zzy/Qt/TTKDownloader-master/build/Desktop_Qt_5_15_0_GCC_64bit-Debug/bin/2.8.0.0/TTKService.sh: not found
20:40:18: /home/zzy/Qt/TTKDownloader-master/build/Desktop_Qt_5_15_0_GCC_64bit-Debug/bin/TTKDownloader 退出，退出代码: 0
 {1 ?} {2?}

**Comment by Greedysky** [comment]
1.QtCreator编译的程序，直接运行TTKService
2.命令行编译，进入TTKUtils目录，sh resource.sh ../TTKResource/ 你的编译生成目录/bin/2.8.0.0
