### ISSUE TITLE
半透明效果导致UI重叠

### ISSUE THREAD

**Issue by Longxr** [Greedysky/TTKDownloader#6]
1.在左边来回点击正在下载已完成，右边切换的页面叠到一起了，上方功能按钮也是
2.系统设置弹出的界面标题栏是透明的，无法拖动

**Comment by Greedysky** [comment]
你这种情况是没有主题文件MTheme，加上就没问题了。

**Comment by Longxr** [comment]
已下载皮肤文件，使用正常，效果很赞
