### ISSUE TITLE
使用qt5.5.1-windows-mingw static32无法编译通过

### ISSUE THREAD

**Issue by orestonce** [Greedysky/TTKDownloader#7]
![捕获](https://user-images.githubusercontent.com/6974828/56811937-78907300-686c-11e9-9546-a31a2818609d.PNG)
使用动态链接是可以通过的, 但是无法下载https链接，http链接下载时字体重叠
![捕获2](https://user-images.githubusercontent.com/6974828/56812273-200da580-686d-11e9-8e46-f7b075f9bc22.PNG)

**Comment by Greedysky** [comment]
字体重叠是没有皮肤 参照 #6

**Comment by Greedysky** [comment]
https 需要手动添加openssl库

**Comment by orestonce** [comment]
谢谢大佬回复
